### PR TITLE
update link

### PR DESCRIPTION
**Pull request by jburel**
This point to EBI binderhub
Tested this am.
We could offer both links if you prefer
cc @YojanaGadiya

### CODE REVIEW

**Comment by YojanaGadiya** [comment]
@jburel Was trying to look at the link, it seems to no be broken. Please take a look when you get time this week.

**Comment by jburel** [comment]
@YojanaGadiya I have tested it and it seems that there is a problem
I will contact the team to see what's going on

**Comment by YojanaGadiya** [comment]
@jburel any update on this?

**Comment by jburel** [comment]
@YojanaGadiya Thanks for re-activating the discussion. I will look at it

**Comment by YojanaGadiya** [comment]
Closing the PR since the link is still not working. We can reopen it once the testing is completed.

**Pull request closed without merging**
